/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/businesses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List published businesses */
        get: operations["listBusinesses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/businesses/{idOrSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get business detail */
        get: operations["getBusinessByIdOrSlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze investor contract for risks */
        post: operations["analyzeContract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Index a knowledge chunk for a business (RAG) */
        post: operations["indexKnowledgeChunk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Initialize a voice assistant session */
        post: operations["createVoiceSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Voice service status */
        get: operations["getVoiceStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get or create demo investor user */
        get: operations["getDemoUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SuccessResponse: {
            /** @example true */
            success: boolean;
        };
        ErrorResponse: {
            /** @example false */
            success: boolean;
            error: string;
            details?: Record<string, never>;
        };
        HealthResponse: {
            /** @example ok */
            status?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        /** @enum {string} */
        UserRole: "FOUNDER" | "INVESTOR";
        /** @enum {string} */
        VisualSceneType: "market_size" | "traction" | "revenue" | "team" | "generic";
        /** @enum {string} */
        VisualSceneEmotion: "confident" | "calm" | "urgent" | "visionary";
        User: {
            /** @example clz1abc2300004iyk9xyz1mno */
            id: string;
            /** Format: email */
            email: string;
            name: string;
            role: components["schemas"]["UserRole"];
            avatarUrl?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        BusinessSummary: {
            id: string;
            name: string;
            slug: string;
            tagline?: string | null;
            industry?: string | null;
            logoUrl?: string | null;
            fundingAsk?: number | null;
            fundingCurrency?: string | null;
            isPublished: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        Business: components["schemas"]["BusinessSummary"] & {
            ownerId?: string;
            description?: string | null;
            marketSize?: string | null;
            /** @description Structured traction data (metrics, growth) */
            traction?: Record<string, never> | null;
            /** @description Structured revenue data (historical, projections) */
            revenue?: Record<string, never> | null;
            /** @description Team structure and key members */
            teamInfo?: Record<string, never> | null;
            businessModel?: string | null;
            websiteUrl?: string | null;
            /** Format: date-time */
            updatedAt?: string;
            owner?: components["schemas"]["User"];
        };
        VisualScene: {
            type: components["schemas"]["VisualSceneType"];
            emotion: components["schemas"]["VisualSceneEmotion"];
            data: {
                [key: string]: unknown;
            };
        };
        ContractRisk: {
            /** @enum {string} */
            severity: "low" | "medium" | "high" | "critical";
            clause: string;
            description: string;
        };
        ContractAnalysisResult: {
            /** @description Narrative risk summary from AI */
            riskFeedback: string;
            /** @description Questions investor can ask via voice assistant */
            recommendedQuestions: string[];
            risks?: components["schemas"]["ContractRisk"][] | null;
        };
        VoiceSessionResponse: {
            sessionId?: string | null;
            businessId?: string | null;
            userId?: string | null;
            /** @description WebSocket URL for live voice (when implemented) */
            wsUrl?: string | null;
            message?: string;
        };
        AnalyzeContractRequest: {
            /** @description Full text of the investor contract */
            contractText: string;
            /** @description Optional business context */
            businessId?: string;
        };
        IndexKnowledgeRequest: {
            businessId: string;
            content: string;
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        VoiceSessionRequest: {
            businessId?: string;
            userId?: string;
        };
    };
    responses: {
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Request validation failed */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"] & {
                    /** @description Zod flatten() error details */
                    details?: Record<string, never>;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is running */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listBusinesses: {
        parameters: {
            query?: {
                /** @description Filter by industry */
                industry?: string;
                limit?: number;
                /** @description Cursor for pagination (last business id) */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of published businesses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["BusinessSummary"][];
                    };
                };
            };
        };
    };
    getBusinessByIdOrSlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Business cuid or slug */
                idOrSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Business detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["Business"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    analyzeContract: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeContractRequest"];
            };
        };
        responses: {
            /** @description Contract analysis result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["ContractAnalysisResult"];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
        };
    };
    indexKnowledgeChunk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndexKnowledgeRequest"];
            };
        };
        responses: {
            /** @description Chunk indexed successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: {
                            chunkId?: string;
                        };
                    };
                };
            };
            400: components["responses"]["ValidationError"];
        };
    };
    createVoiceSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoiceSessionRequest"];
            };
        };
        responses: {
            /** @description Voice session created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["VoiceSessionResponse"];
                    };
                };
            };
        };
    };
    getVoiceStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Voice service status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        status?: string;
                    };
                };
            };
        };
    };
    getDemoUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Demo user info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: {
                            userId?: string;
                        };
                    };
                };
            };
        };
    };
}
