/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register/founder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register as a founder */
        post: operations["registerFounder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register/investor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register as an investor */
        post: operations["registerInvestor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login and get JWT token */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout (invalidate token client-side) */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/businesses/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current owner's business */
        get: operations["getMyBusiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/businesses/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit business verification */
        post: operations["verifyBusiness"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/businesses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List published businesses (marketplace) */
        get: operations["listBusinesses"];
        put?: never;
        /** Create a new business (founder only) */
        post: operations["createBusiness"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/businesses/{idOrSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get business detail */
        get: operations["getBusinessByIdOrSlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/businesses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update business (founder/owner only) */
        patch: operations["updateBusiness"];
        trace?: never;
    };
    "/api/businesses/{id}/investors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List investors who have a deal with this business */
        get: operations["getBusinessInvestors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all investors */
        get: operations["listInvestors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single investor profile with their deals */
        get: operations["getInvestor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/businesses/{id}/knowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List knowledge chunks for a business */
        get: operations["listKnowledge"];
        put?: never;
        /** Upload & embed knowledge chunk (founder only) */
        post: operations["uploadKnowledge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/businesses/{id}/knowledge/{chunkId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a knowledge chunk */
        delete: operations["deleteKnowledgeChunk"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a new conversation with a business AI avatar (investor only) */
        post: operations["createConversation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{id}/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a message to the AI avatar (RAG + Gemini) */
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get conversation message history */
        get: operations["getMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/legal/generate-term-sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate AI term sheet draft */
        post: operations["generateTermSheet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/legal/analyze-document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload & analyze a contract document */
        post: operations["analyzeDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new deal */
        post: operations["createDeal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get deal detail */
        get: operations["getDeal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deals/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export deal document to .docx */
        get: operations["exportDeal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SuccessResponse: {
            /** @example true */
            success: boolean;
        };
        ErrorResponse: {
            /** @example false */
            success: boolean;
            error: string;
            details?: Record<string, never>;
        };
        /** @enum {string} */
        UserRole: "FOUNDER" | "INVESTOR";
        /** @enum {string} */
        BusinessStage: "IDEA" | "PRE_SEED" | "SEED" | "SERIES_A";
        /** @enum {string} */
        DealStatus: "DRAFT" | "NEGOTIATING" | "SIGNED" | "CANCELLED";
        /** @enum {string} */
        DocumentType: "TERM_SHEET" | "CONTRACT" | "OTHER";
        /** @enum {string} */
        BusinessVerificationStatus: "DRAFT" | "PENDING" | "VERIFIED" | "REJECTED";
        /** @enum {string} */
        VisualSceneType: "market_size" | "traction" | "revenue" | "team" | "generic";
        /** @enum {string} */
        VisualSceneEmotion: "confident" | "calm" | "urgent" | "visionary";
        /** @enum {string} */
        RiskSeverity: "low" | "medium" | "high" | "critical";
        User: {
            id: string;
            /** Format: email */
            email: string;
            name: string;
            role: components["schemas"]["UserRole"];
            avatarUrl?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        BusinessSummary: {
            id: string;
            name: string;
            slug: string;
            tagline?: string | null;
            industry?: string | null;
            stage?: components["schemas"]["BusinessStage"];
            logoUrl?: string | null;
            fundingAsk?: number | null;
            fundingCurrency?: string | null;
            isPublished: boolean;
            verificationStatus: components["schemas"]["BusinessVerificationStatus"];
            /** Format: date-time */
            createdAt: string;
        };
        Business: components["schemas"]["BusinessSummary"] & {
            ownerId?: string;
            description?: string | null;
            websiteUrl?: string | null;
            /** Format: date-time */
            updatedAt?: string;
            owner?: components["schemas"]["User"];
        };
        KnowledgeChunk: {
            id: string;
            businessId: string;
            content: string;
            /** @example pitch_deck */
            sourceLabel?: string | null;
            tokenCount?: number | null;
            /** Format: date-time */
            createdAt: string;
        };
        Conversation: {
            id: string;
            investorId: string;
            businessId: string;
            title?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
            business?: components["schemas"]["BusinessSummary"];
        };
        VisualScene: {
            type: components["schemas"]["VisualSceneType"];
            emotion: components["schemas"]["VisualSceneEmotion"];
            data: {
                [key: string]: unknown;
            };
        };
        Message: {
            id: string;
            conversationId: string;
            senderId?: string | null;
            content: string;
            /** @enum {string} */
            role: "user" | "assistant" | "system";
            visualScene?: components["schemas"]["VisualScene"] | null;
            /** Format: date-time */
            createdAt: string;
        };
        MessageResponse: {
            messageId: string;
            /** @example assistant */
            role: string;
            content: string;
            visualScene?: components["schemas"]["VisualScene"] | null;
        };
        RiskFlag: {
            /** @example Section 4.2 - Drag Along Rights */
            clause: string;
            severity: components["schemas"]["RiskSeverity"];
            explanation: string;
        };
        DocumentAnalysisResponse: {
            documentId: string;
            summary: string;
            riskFlags: components["schemas"]["RiskFlag"][];
            missingClauses: string[];
            riskScore: number;
            /** @example AI-generated analysis. Please consult a licensed attorney. */
            disclaimer?: string;
        };
        TermSheetResponse: {
            documentId: string;
            termSheetMarkdown: string;
            /** @example AI-generated draft. Please consult a licensed attorney. */
            disclaimer: string;
        };
        Deal: {
            id: string;
            businessId: string;
            investorId: string;
            preMoneyValuation?: number | null;
            investmentAmount?: number | null;
            equityPct?: number | null;
            vestingMonths?: number | null;
            liquidationPref?: string | null;
            status: components["schemas"]["DealStatus"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        DealDocument: {
            id: string;
            type: components["schemas"]["DocumentType"];
            riskScore: number | null;
            fileUrl?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        DealDetail: components["schemas"]["Deal"] & {
            business?: components["schemas"]["BusinessSummary"];
            investor?: components["schemas"]["User"];
            documents?: components["schemas"]["DealDocument"][];
        };
        RegisterRequest: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        AuthResponse: {
            user: components["schemas"]["User"];
            token: string;
        };
        CreateBusinessRequest: {
            name: string;
            tagline?: string;
            description?: string;
            industry?: string;
            stage?: components["schemas"]["BusinessStage"];
            fundingAsk?: number;
            /** @default IDR */
            fundingCurrency: string;
            logoUrl?: string;
            websiteUrl?: string;
        };
        UpdateBusinessRequest: {
            name?: string;
            tagline?: string;
            description?: string;
            industry?: string;
            stage?: components["schemas"]["BusinessStage"];
            fundingAsk?: number;
            fundingCurrency?: string;
            logoUrl?: string;
            websiteUrl?: string;
            isPublished?: boolean;
        };
        UploadKnowledgeRequest: {
            content: string;
            /**
             * @description Source label e.g. "pitch_deck", "financials", "team"
             * @example pitch_deck
             */
            sourceLabel?: string;
        };
        CreateConversationRequest: {
            businessId: string;
        };
        SendMessageRequest: {
            message: string;
        };
        GenerateTermSheetRequest: {
            dealId: string;
            preMoneyValuation: number;
            investmentAmount: number;
            equityPct: number;
            /** @default 48 */
            vestingMonths: number;
            /** @default 1x non-participating */
            liquidationPref: string;
        };
        AnalyzeDocumentRequest: {
            /**
             * Format: binary
             * @description PDF or DOCX file
             */
            file: string;
            /** @description Optional deal context */
            dealId?: string;
        };
        CreateDealRequest: {
            businessId: string;
        };
        VerifyBusinessRequest: {
            ownerName: string;
            /** @enum {string} */
            businessLocation: "INDONESIA" | "MALAYSIA" | "SINGAPORE" | "THAILAND" | "PHILIPPINES" | "VIETNAM" | "BRUNEI" | "CAMBODIA" | "LAOS" | "MYANMAR";
            businessDescription: string;
            businessModel: string;
            additionalDocuments?: string[] | null;
        };
        BusinessInvestor: {
            investor: {
                id: string;
                name: string;
                /** Format: email */
                email: string;
                avatarUrl?: string | null;
                /** Format: date-time */
                createdAt: string;
            };
            deal: {
                id: string;
                status: components["schemas"]["DealStatus"];
                investmentAmount?: number | null;
                equityPct?: number | null;
                preMoneyValuation?: number | null;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
            };
        };
        InvestorProfile: {
            id: string;
            name: string;
            /** Format: email */
            email: string;
            avatarUrl?: string | null;
            /** @description Total number of deals */
            totalDeals: number;
            /** @description Number of NEGOTIATING or SIGNED deals */
            activeDeals: number;
            /** Format: date-time */
            createdAt: string;
        };
        InvestorDetail: components["schemas"]["InvestorProfile"] & {
            deals?: {
                id: string;
                status: components["schemas"]["DealStatus"];
                investmentAmount?: number | null;
                equityPct?: number | null;
                preMoneyValuation?: number | null;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
                business: {
                    id: string;
                    name: string;
                    slug: string;
                    logoUrl?: string | null;
                    industry?: string | null;
                    stage?: components["schemas"]["BusinessStage"];
                };
            }[];
        };
    };
    responses: {
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Request validation failed */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Missing or invalid JWT token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Insufficient permissions */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource already exists */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is running */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /** Format: date-time */
                        timestamp?: string;
                    };
                };
            };
        };
    };
    registerFounder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Founder registered successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["AuthResponse"];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            409: components["responses"]["Conflict"];
        };
    };
    registerInvestor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Investor registered successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["AuthResponse"];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            409: components["responses"]["Conflict"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["AuthResponse"];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: {
                            /** @example Logged out successfully */
                            message?: string;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMyBusiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owner's business */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["BusinessSummary"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    verifyBusiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyBusinessRequest"];
            };
        };
        responses: {
            /** @description Verification submitted, status set to PENDING */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: {
                            id?: string;
                            verificationStatus?: components["schemas"]["BusinessVerificationStatus"];
                        };
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listBusinesses: {
        parameters: {
            query?: {
                /** @description Filter by industry */
                industry?: string;
                /** @description Filter by funding stage */
                stage?: components["schemas"]["BusinessStage"];
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of published businesses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["BusinessSummary"][];
                        total?: number;
                        page?: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createBusiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBusinessRequest"];
            };
        };
        responses: {
            /** @description Business created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["BusinessSummary"];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getBusinessByIdOrSlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Business cuid or slug */
                idOrSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Business detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["Business"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateBusiness: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBusinessRequest"];
            };
        };
        responses: {
            /** @description Business updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["BusinessSummary"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getBusinessInvestors: {
        parameters: {
            query?: {
                /** @description Filter by deal status */
                status?: components["schemas"]["DealStatus"];
                page?: number;
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Business id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of investors with deal info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["BusinessInvestor"][];
                        total?: number;
                        page?: number;
                        limit?: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listInvestors: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of investors */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["InvestorProfile"][];
                        total?: number;
                        page?: number;
                        limit?: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getInvestor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Investor user id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Investor profile with deal history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["InvestorDetail"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listKnowledge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of knowledge chunks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["KnowledgeChunk"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    uploadKnowledge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadKnowledgeRequest"];
            };
        };
        responses: {
            /** @description Knowledge embedded successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: {
                            /** @example 4 */
                            chunksCreated?: number;
                            /** @example Knowledge embedded successfully */
                            message?: string;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    deleteKnowledgeChunk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                chunkId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chunk deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createConversation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversationRequest"];
            };
        };
        responses: {
            /** @description Conversation started */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["Conversation"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Conversation id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description AI response with visual scene */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["MessageResponse"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getMessages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["Message"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    generateTermSheet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateTermSheetRequest"];
            };
        };
        responses: {
            /** @description Term sheet generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["TermSheetResponse"];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
        };
    };
    analyzeDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["AnalyzeDocumentRequest"];
            };
        };
        responses: {
            /** @description Document analysis result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["DocumentAnalysisResponse"];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createDeal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDealRequest"];
            };
        };
        responses: {
            /** @description Deal created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["Deal"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getDeal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deal detail with documents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["DealDetail"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    exportDeal: {
        parameters: {
            query: {
                /** @description Document id to export */
                documentId: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description .docx file download */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
